gui:
  skipRewordInEditorWarning: true
  nerdFontsVersion: "3"
  border: 'single'
  # Upstream: https://github.com/vague-theme/vague-lazygit/blob/main/vague.yml
  authorColors:
    "*": "#f3be7c"
  theme:
    activeBorderColor:
      - "#aeaed1"
      - "bold"
    inactiveBorderColor:
      - "#606079"
    optionsTextColor:
      - "#606079"
    selectedLineBgColor:
      - "#252530"
    cherryPickedCommitFgColor:
      - "#d8647e"
    cherryPickedCommitBgColor:
      - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"
os:
  editPreset: 'nvim' # see 'Configuring File Editing' section
git:
  pagers:
    - # delta
      colorArg: always
      pager: delta --dark --paging=never
      # ydiff
      # colorArg: never
      # pager: ydiff -p cat -s --wrap --width={{columnWidth}}
  overrideGpg: true
